version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/code_pipeline_nginx
    overwrite: yes

permissions:
  - object: /
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: /Scripts/beforeInstall.bash
      timeout: 300
      runas: root
  ApplicationStart:
    - location: /Scripts/deploy.sh
      timeout: 300
      runas: root
